name: python-playwrightenv
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.11.9
  - python_abi=3.11
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - colorama==0.4.6
    - greenlet==3.0.3
    - idna==3.7
    - iniconfig==2.0.0
    - jinja2==3.1.4
    - markupsafe==2.1.5
    - packaging==24.1
    - playwright==1.45.0
    - pluggy==1.5.0
    - pyee==11.1.0
    - pytest==8.3.1
    - pytest-asyncio==0.23.8
    - pytest-base-url==2.1.0
    - pytest-html==4.1.1
    - pytest-metadata==3.1.1
    - pytest-playwright==0.5.1
    - python-slugify==8.0.4
    - requests==2.32.3
    - text-unidecode==1.3
    - urllib3==2.2.2
